AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vimagemore

  Sample SAM Template for vimagemore
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  UploaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: uploader/
      Handler: dst/app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        Uploader:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /upload
            Method: post
      Environment:
        Variables:
          VIMAGEMORE_BUCKET_NAME: !Ref VimagemoreBucket
          VIMAGEMORE_BUCKET_URL: !GetAtt VimagemoreBucket.WebsiteURL
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref VimagemoreBucket
  VimagemoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite # 個別にACLでpublic-readを付与する想定
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      LoggingConfiguration:
        LogFilePrefix: logs/

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UploaderApi:
    Description: "API Gateway endpoint URL for Prod stage for Uploader function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/"
  UploaderFunction:
    Description: "Uploader Lambda Function ARN"
    Value: !GetAtt UploaderFunction.Arn
  UploaderFunctionIamRole:
    Description: "Implicit IAM Role created for Uploader function"
    Value: !GetAtt UploaderFunctionRole.Arn
